/**
 * Regenerates `src/atomic/propertyGroups.generated.ts` from `mdn-data`: every CSS shorthand and
 * the longhands it sets (camelCased, as vanilla-extract style objects spell them).
 *
 *   node scripts/generatePropertyGroups.ts
 *
 * The logical ↔ physical property groups and the property aliases are hand-written in
 * `src/atomic/propertyGroups.ts`, next to the overlap logic that consumes both.
 */
import fs from 'node:fs'
import {createRequire} from 'node:module'
import path from 'node:path'

const require = createRequire(import.meta.url)

interface MdnProperty {
  computed: string | string[]
}

const properties: Record<string, MdnProperty> = require('mdn-data/css/properties.json')

/**
 * `border-top-color` → `borderTopColor`, `-webkit-mask` → `WebkitMask`, `-ms-flex` → `msFlex`:
 * the csstype spelling vanilla-extract style objects use (and `dashify` in the renderer
 * reverses).
 */
const camelCase = (property: string): string =>
  property
    .replace(/^-ms-/, 'ms-')
    .replace(
      /^-(webkit|moz|o)-/,
      (_, vendor: string) => `${vendor[0]?.toUpperCase()}${vendor.slice(1)}-`,
    )
    .replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())

/**
 * Shorthands `mdn-data` doesn't (yet) model as shorthands: `computed` is a keyword instead of
 * the longhand list.
 */
const overrides: Record<string, string[]> = {
  'white-space': ['white-space-collapse', 'text-wrap-mode'],
  'font-synthesis': [
    'font-synthesis-weight',
    'font-synthesis-style',
    'font-synthesis-small-caps',
    'font-synthesis-position',
  ],
  'font-variant': [
    'font-variant-alternates',
    'font-variant-caps',
    'font-variant-east-asian',
    'font-variant-emoji',
    'font-variant-ligatures',
    'font-variant-numeric',
    'font-variant-position',
  ],
  // The `font` shorthand also resets the font sub-properties it cannot express (CSS Fonts 4)
  'font': [
    'font-style',
    'font-variant',
    'font-weight',
    'font-stretch',
    'font-size',
    'line-height',
    'font-family',
    'font-size-adjust',
    'font-kerning',
    'font-language-override',
    'font-feature-settings',
    'font-optical-sizing',
    'font-variation-settings',
  ],
  // Logical border side shorthands `mdn-data` describes by their computed color/style/width
  'border-block-color': ['border-block-start-color', 'border-block-end-color'],
  'border-block-style': ['border-block-start-style', 'border-block-end-style'],
  'border-block-width': ['border-block-start-width', 'border-block-end-width'],
  'border-inline-color': ['border-inline-start-color', 'border-inline-end-color'],
  'border-inline-style': ['border-inline-start-style', 'border-inline-end-style'],
  'border-inline-width': ['border-inline-start-width', 'border-inline-end-width'],
  // ...and the per-side ones by the physical `border-width`/`border-style` (or, for
  // `border-block-end`, the `border-top-*` longhands), which would let `borderBlockEnd` slip
  // past `borderBottomWidth` in the overlap check
  'border-block-start': [
    'border-block-start-width',
    'border-block-start-style',
    'border-block-start-color',
  ],
  'border-block-end': [
    'border-block-end-width',
    'border-block-end-style',
    'border-block-end-color',
  ],
  'border-inline-start': [
    'border-inline-start-width',
    'border-inline-start-style',
    'border-inline-start-color',
  ],
  'border-inline-end': [
    'border-inline-end-width',
    'border-inline-end-style',
    'border-inline-end-color',
  ],
  // `outline` resets `outline-offset` in practice (matching StyleX's resolution table)
  'outline': ['outline-width', 'outline-style', 'outline-color', 'outline-offset'],
  // Legacy per-axis longhands some engines still accept
  'scroll-snap-type': ['scroll-snap-type-x', 'scroll-snap-type-y'],
}

const shorthands = new Map<string, string[]>()
for (const [name, property] of Object.entries(properties)) {
  const longhands = overrides[name] ?? property.computed
  if (Array.isArray(longhands) && longhands.length > 0) {
    shorthands.set(name, longhands)
  }
}
for (const [name, longhands] of Object.entries(overrides)) {
  if (!shorthands.has(name)) shorthands.set(name, longhands)
}

const sorted = Array.from(shorthands.entries()).toSorted(([a], [b]) => a.localeCompare(b))

const lines = [
  '/**',
  ' * Generated by `scripts/generatePropertyGroups.ts` from `mdn-data` — do not edit by hand.',
  ' *',
  ' * Every CSS shorthand and the longhands it sets (which may be shorthands themselves, e.g.',
  ' * `border` → `borderWidth`), camelCased like vanilla-extract style objects spell them.',
  ' */',
  '',
  'export const SHORTHAND_LONGHANDS: Readonly<Record<string, ReadonlyArray<string>>> = {',
  ...sorted.map(
    ([name, longhands]) =>
      `  ${camelCase(name)}: [${longhands.map((longhand) => `'${camelCase(longhand)}'`).join(', ')}],`,
  ),
  '}',
  '',
]

const outputPath = path.resolve(import.meta.dirname, '../src/atomic/propertyGroups.generated.ts')
fs.mkdirSync(path.dirname(outputPath), {recursive: true})
fs.writeFileSync(outputPath, lines.join('\n'))
console.warn(`Wrote ${sorted.length} shorthands to ${path.relative(process.cwd(), outputPath)}`)
