packages:
  - packages/@sanity/*
  - playground/*
  - packages/@sanity/pkg-utils/test/env/__tmp__/**

catalog:
  '@sanity/client': ^7.13.1
  '@sanity/icons': ^3.7.4
  '@sanity/logos': ^2.2.2
  '@typescript/native-preview': 7.0.0-dev.20251125.1
  typescript: 5.9.3

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@next/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@rollup/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - '@vite/*'
  - '@vitest/*'
  - 'csstype'
  - 'groq'
  - 'next'
  - 'oxlint'
  - 'oxlint-tsgolint'
  - 'rollup'
  - 'sanity'
  - 'vite'
  - 'vitest'

overrides:
  '@sanity/pkg-utils': workspace:*

# This is needed for prettier to be able to use the plugin specified by the `@sanity/prettier-config` preset
publicHoistPattern:
  - '*prettier*'

trustPolicy: 'no-downgrade'
trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@sanity/sdk@2.1.2'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - vite@6.4.1
