packages:
  - playground/**
  - test/env/__tmp__/**

catalog:
  '@sanity/client': ^7.8.0
  '@sanity/icons': ^3.7.4
  '@sanity/logos': ^2.2.1
  '@typescript/native-preview': 7.0.0-dev.20250730.1
  typescript: 5.8.3
