packages:
  - packages/@sanity/*
  - playground/*
  - packages/@sanity/tsdown-config/test/fixtures/**

catalog:
  '@sanity/client': ^7.14.1
  '@sanity/icons': ^3.7.4
  '@sanity/logos': ^2.2.2
  '@types/node': ^24.10.9
  '@typescript/native-preview': 7.0.0-dev.20260127.1
  publint: ^0.3.17
  tsdown: ^0.20.1
  typescript: 5.9.3
  vitest: ^4.0.18

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@next/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@rollup/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - '@vite/*'
  - '@vitest/*'
  - csstype
  - groq
  - groq-js
  - next
  - oxlint
  - oxlint-tsgolint
  - react
  - react-dom
  - react-is
  - rollup
  - sanity
  - vite
  - vitest
  # Renovate security update: lodash-es@4.17.23
  - lodash-es@4.17.23
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23

overrides:
  '@sanity/pkg-utils': workspace:*

# This is needed for prettier to be able to use the plugin specified by the `@sanity/prettier-config` preset
publicHoistPattern:
  - '*prettier*'

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@sanity/sdk@2.1.2'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - vite@6.4.1
