packages:
  - playground/**
  - test/env/__tmp__/**

catalog:
  '@sanity/client': ^7.8.0
  '@sanity/icons': ^3.7.4
  '@sanity/logos': ^2.2.1
  '@typescript/native-preview': 7.0.0-dev.20250916.1
  typescript: 5.9.2

overrides:
  '@sanity/pkg-utils': workspace:*

# This is needed for prettier to be able to use the plugin specified by the `@sanity/prettier-config` preset
publicHoistPattern:
  - '*prettier*'
