/** @public */
export interface PkgExport {
  /** @internal */
  _exported?: boolean
  browser?: {
    source: string
    import?: string
    require?: string
    default?: string
  }
  // electron?: {
  //   node?: string
  //   default?: string
  // }
  node?: {
    source?: string
    import?: string
    require?: string
    default?: string
  }
  types?: string
  source: string
  development?: string
  monorepo?: string
  import?: string
  require?: string
  default: string
}

/** @public */
export interface PkgExports {
  [path: string]: PkgExport
}

/**
 * A `.css` export subpath that declares a `source`: a stylesheet the CSS pipeline compiles into
 * `dist`, rather than a JS entry. The remaining conditions (`types`, `browser`, `style`,
 * `node`, `default`) are generated by the build - hand-written ones are validated against what
 * the build would produce.
 * @public
 */
export interface PkgCssExport {
  /** The stylesheet compiled for this subpath, e.g. `./src/ui/styles.css`. */
  source: string
  /** Any hand-written export conditions, in their authored order. */
  [condition: string]: string | undefined
}

/** @public */
export interface PackageJSON {
  type?: 'commonjs' | 'module' | undefined
  version: string
  private?: boolean
  author?: string | {name: string; email?: string; url?: string}
  name: string
  description?: string
  keywords?: string[]
  bin?: Record<string, string>
  dependencies?: Record<string, string | undefined>
  devDependencies?: Record<string, string | undefined>
  peerDependencies?: Record<string, string | undefined>
  exports?: Record<
    string,
    | `./${string}.json`
    | `./${string}.css`
    | {
        source?: string
        development?: string
        monorepo?: string
        types?: string
        browser?: {
          source: string
          import?: string
          require?: string
          default?: string
        }
        node?: {
          source?: string
          module?: string
          import?: string
          require?: string
          default?: string
        }
        module?: string
        import?: string
        require?: string
        default: string
      }
    | {
        types?: string
        svelte: string
        default?: string
      }
  >
  publishConfig?: {
    access?: 'public' | 'restricted'
    registry?: string
    tag?: string
    exports?: Record<
      string,
      | string
      | {
          types?: string
          /**
           * A runtime condition may be condensed to a plain string when only one target is left to
           * resolve to: `"browser": "./dist/index.browser.js"` and
           * `"browser": {"default": "./dist/index.browser.js"}` resolve identically.
           */
          browser?:
            | string
            | {
                import?: string
                require?: string
                default?: string
              }
          node?:
            | string
            | {
                import?: string
                require?: string
                default?: string
              }
          import?: string
          require?: string
          default: string
        }
      | {
          types?: string
          svelte: string
          default?: string
        }
    >
    /**
     * Any other npm config option applied at publish time.
     * Undocumented and not guaranteed to be stable.
     */
    [npmConfigKey: string]: unknown
  }
  main?: string
  browser?: Record<string, string>
  source?: string
  module?: string
  types?: string
  typesVersions?: Record<string, Record<string, string[]>>
  files?: string[]
  scripts?: Record<string, string | undefined>
  browserslist?: string | string[]
  sideEffects?: boolean | string[]
  engines?: {
    node?: string
    npm?: string
  }
  repository?: string | {type: 'git'; url: string}
  bugs?: string | {url: string; email?: string}
  homepage?: string
  license?: string
}
