import {parseCssExports, parseExports, type PackageJSON} from '@sanity/parse-package-json'
import {describe, expect, test} from 'vitest'

const base = {
  type: 'module',
  name: 'test',
  version: '0.0.0-test',
  license: 'MIT',
} as const satisfies Partial<PackageJSON>

// `PackageJSON['exports']` models the shapes authored by hand; a conditional CSS export is a
// flat condition -> path map, which `parsePackage` passes through untouched.
const pkgWith = (exports: Record<string, unknown>): PackageJSON =>
  // oxlint-disable-next-line no-unsafe-type-assertion
  ({...base, exports}) as unknown as PackageJSON

describe('parseCssExports', () => {
  test('returns `.css` subpaths that declare a `source`', () => {
    const pkg = pkgWith({
      '.': {source: './src/index.ts', default: './dist/index.js'},
      './ui/styles.css': {source: './src/ui/styles.css'},
      './package.json': './package.json',
    })

    expect(parseCssExports({pkg})).toEqual([
      {_path: './ui/styles.css', source: './src/ui/styles.css'},
    ])
  })

  test('carries hand-written conditions along, in their authored order', () => {
    const pkg = pkgWith({
      './ui/styles.css': {
        source: './src/ui/styles.css',
        types: './dist/ui/styles-css.d.ts',
        browser: './dist/ui/styles.css',
        style: './dist/ui/styles.css',
        node: './dist/ui/styles-css.js',
        default: './dist/ui/styles-css.js',
      },
    })

    const [cssExport] = parseCssExports({pkg})
    expect(Object.keys(cssExport!)).toEqual([
      'source',
      'types',
      'browser',
      'style',
      'node',
      'default',
      '_path',
    ])
    expect(cssExport).toMatchObject({browser: './dist/ui/styles.css'})
  })

  test('ignores `.css` subpaths without a `source`', () => {
    // A plain passthrough export ships the file as-is, and the conditional export generated by
    // `exports.nodeCompat` has no source to build from
    const pkg = pkgWith({
      './css/styles.css': './src/css/styles.css',
      './bundle.css': {
        types: './dist/bundle-css.d.ts',
        browser: './dist/bundle.css',
        node: './dist/bundle-css.js',
        default: './dist/bundle-css.js',
      },
    })

    expect(parseCssExports({pkg})).toEqual([])
  })

  test('returns an empty list without `exports`', () => {
    expect(parseCssExports({pkg: {...base}})).toEqual([])
  })
})

describe('parseExports', () => {
  test('leaves `.css` subpaths to `parseCssExports`', () => {
    // A `.css` subpath is a stylesheet, not a JS entry: picking it up here would derive an
    // entry alias from its `default` condition (the no-op shim) and build it as JS.
    const pkg = pkgWith({
      '.': {source: './src/index.ts', default: './dist/index.js'},
      './ui/styles.css': {source: './src/ui/styles.css', default: './dist/ui/styles-css.js'},
    })

    expect(parseExports({pkg}).map((exportEntry) => exportEntry._path)).toEqual(['.'])
  })
})
